### ISSUE TITLE
Button Component

### ISSUE THREAD

**Issue by thejhh** [sendanor/hyperstack#13]
### Requirements

* [ ] Must support optional icon
* [ ] Must support optional text
* [ ] Must support user defined multiple style sets (primary, secondary, warning, error, transparent...)
    * [ ] Must support font name
    * [ ] Must support font weight
    * [ ] Must support optional border radius
    * [ ] Must support optional border size
    * [ ] Must support text color
    * [ ] Must support background style

### TODO

* [ ] Design button component
* [ ] Implement button component
* [ ] Document button component

### See also

* #14
