### ISSUE TITLE
Azure AD Login button

### ISSUE THREAD

**Issue by thejhh** [sendanor/hyperstack#14]
![Image](https://github.com/sendanor/hyperstack/assets/905840/54292b2c-2959-4b01-87fe-73beb03742d2)

### TODO

 * [ ] Vertically aligned icon and text
 * [ ] Font: Segoe UI Regular 15 px
 * [ ] Font weight: 600
 * [ ] 41px height
 * [ ] 12 px spacing
 * [ ] Dark mode
     * [ ] Font color: `#FFFFFF`
     * [ ] Background: `#2F2F2F`
 * [ ] Light mode
     * [ ] Font color: `#5E5E5E`
     * [ ] Background: `#FFFFFF`
     * [ ] Border: 1px `#8C8C8C`

### See also

* #13 
* [Branding guidelines for applications](https://learn.microsoft.com/en-us/azure/active-directory/develop/howto-add-branding-in-apps)
