### ISSUE TITLE
possible issue with populateHyperDTO

### ISSUE THREAD

**Issue by thejhh** [sendanor/hyperstack#35]
This function uses `HttpService.getJson()` to fetch an external resource. 

The function must be changed so that it doesn't load the resource if it already exists in the array.

### TODO 

* [x] The implementation must be changed to not fetch the resource again if it already exists within the array.
* [ ] Add unit tests
* [x] Fix possible security issue

### Possible security issue

There might be an (security) bug if the referenced address would return something that isn't named with the URL itself. 

So we probably would need to either:

 1. rename the resource with the URL automatically (this would make it possible to reuse same resources from different URLs) and/or 
 2. throw an exception if the content's name doesn't match the address in the URL

The name and extends would need to match anyway.
